doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        url: '%env(DATABASE_URL)%'
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            uuid_binary:  Ramsey\Uuid\Doctrine\UuidBinaryType
        mapping_types:
           uuid_binary: binary

    orm:
        auto_generate_proxy_classes:  '%kernel.debug%'
